import Head from "next/head";
import Image from "next/image";
import { useSession } from "next-auth/react";
import { LoginButton } from "../components/login-btn";

export default function Home() {
  const { data: session, status } = useSession();
  const loading = status === "loading";

  return (
    <div>
      <Head>
        <title>Authentication-App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          {loading && <div>Loading...</div>}
          <p>Hello</p>
          <LoginButton />
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
