import Head from "next/head";
import Image from "next/image";
import { useSession } from "next-auth/react";
import { Header } from "../components/Header";

export default function Home() {
  const { data: session, status } = useSession();
  const loading = status === "loading";

  return (
    <div>
      <Head>
        <title>Authentication-App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <div>
          {loading && <div>Loading...</div>}
          {session && (
            <>
              <h1>Welcome, {session.user.name ?? session.user.email}!</h1>
              <Image
                src={session.user.image}
                alt="user image"
                width="300"
                height="300"
              />
            </>
          )}
          {!session && (
            <>
              <p>Please Log in to Continue</p>
            </>
          )}
          <p>Hello</p>
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
